### ISSUE TITLE
k3s upgrdae fails due to taint on octoprint server node k3s-c

### ISSUE THREAD

**Issue by dkw99** [dkw99/home-ops#427]
Upgrade controller missing node toleration

```
 tolerations:
      - key: "restricted-node"
        operator: "Equal"
        value: "octoprint-server"
        effect: "NoSchedule"
```
