### ISSUE TITLE
K10 - The requested page needs a username and a password

### ISSUE THREAD

**Issue by dkw99** [dkw99/home-ops#75]
helm-release.yaml

Comment out the following lines
auth:
  k10AdminUsers:
    - ${SECRET_EMAIL_ADDRESS}

**Comment by dkw99** [comment]
cluster/core/kasten-io/k10/helm-release.yaml
added 
```
chart:
    spec:
      auth:
        tokenAuth:
          enabled: true
```
